import {
  IconArrowDown,
  IconArrowUp,
  IconCheck,
  IconClipboard,
  IconClipboardCheck,
  IconDashboard,
  IconDots,
  IconEdit,
  IconHome,
  IconLogin,
  IconLogout,
  IconMoon,
  IconPlus,
  IconSearch,
  IconSun,
  IconTrash,
  IconWorld,
  IconX,
  IconSettings,
  IconHistory,
  IconFileDescription,
  IconClockHour4,
  IconClockEdit,
  IconUserCircle,
  IconActivity,
  IconCodeDots,
  IconFileTypePdf,
  IconFileTypeTxt,
  IconAdjustmentsHorizontal,
  IconSend2,
  IconRobotFace,
  IconUser,
  IconChevronDown,
  IconUpload,
  IconPhoto,
  IconReplace,
  IconChevronRight,
  IconBolt,
  IconFiles,
  IconPlayerPause,
  IconPaperclip,
  IconRocket,
  IconBrandDatabricks,
  IconDatabase,
  IconAlertTriangle,
  IconUsersGroup,
  IconFolder,
  IconSpeakerphone,
  IconLayoutSidebarRight,
  IconChevronLeft,
  IconThumbUp,
  IconSparkles,
  IconInfoCircle,
  IconTemperature,
  IconFence,
  IconThumbUpFilled,
  IconLayoutGrid,
  IconFileTypeCsv,
  IconCube,
  IconPackages,
  IconPlayerPlayFilled,
  IconDownload,
  IconWand,
  IconPointFilled,
  IconChartPie,
  IconUsers,
  IconFilter,
} from "@tabler/icons-react";
import { memo, SVGProps } from "react";

//   import Csharp from "@/assets/csharp.svg?react";
//   import Curl from "@/assets/curl.svg?react";
//   import Javascript from "@/assets/javascript.svg?react";
//   import Python from "@/assets/python.svg?react";

export const Icons = {
  CodeDots: memo(IconCodeDots),
  Sun: memo(IconSun),
  Moon: memo(IconMoon),
  Locale: memo(IconWorld),
  Copy: memo(IconClipboard),
  Copied: memo(IconClipboardCheck),
  Asc: memo(IconArrowUp),
  Desc: memo(IconArrowDown),
  Home: memo(IconHome),
  Dashboard: memo(IconDashboard),
  Login: memo(IconLogin),
  Logout: memo(IconLogout),
  Add: memo(IconPlus),
  Edit: memo(IconEdit),
  Delete: memo(IconTrash),
  More: memo(IconDots),
  Expanded: memo(IconPlus),
  Collapsed: memo(IconX),
  Search: memo(IconSearch),
  Check: memo(IconCheck),
  Setting: memo(IconSettings),
  History: memo(IconHistory),
  Detail: memo(IconFileDescription),
  CreatedAt: memo(IconClockHour4),
  UpdatedAt: memo(IconClockEdit),
  Creator: memo(IconUserCircle),
  Status: memo(IconActivity),
  PDF: memo(IconFileTypePdf),
  TXT: memo(IconFileTypeTxt),
  FineTune: memo(IconAdjustmentsHorizontal),
  Send: memo(IconSend2),
  Robot: memo(IconRobotFace),
  User: memo(IconUser),
  ChevronDown: memo(IconChevronDown),
  Upload: memo(IconUpload),
  Photo: memo(IconPhoto),
  Mode: memo(IconReplace),
  RightArrow: memo(IconChevronRight),
  Bolt: memo(IconBolt),
  Files: memo(IconFiles),
  PaperClip: memo(IconPaperclip),
  Pause: memo(IconPlayerPause),
  Rocket: memo(IconRocket),
  LLM: memo(IconBrandDatabricks),
  Dataset: memo(IconDatabase),
  Alert: memo(IconAlertTriangle),
  Groups: memo(IconUsersGroup),
  Folder: memo(IconFolder),
  SpeakerPhone: memo(IconSpeakerphone),
  CollapsePanel: memo(IconLayoutSidebarRight),
  GoBack: memo(IconChevronLeft),
  UpVote: memo(IconThumbUp),
  UpVoteFilled: memo(IconThumbUpFilled),
  Sparkle: memo(IconSparkles),
  Info: memo(IconInfoCircle),
  Temperature: memo(IconTemperature),
  Threshold: memo(IconFence),
  ChatMode: memo(IconLayoutGrid),
  CSV: memo(IconFileTypeCsv),
  Model: memo(IconCube),
  ModelRelease: memo(IconPackages),
  Start: memo(IconPlayerPlayFilled),
  Download: memo(IconDownload),
  Wand: memo(IconWand),
  Point: memo(IconPointFilled),
  Pie: memo(IconChartPie),
  Users: memo(IconUsers),
  Filter: memo(IconFilter),
};

//   interface Props extends SVGProps<SVGSVGElement> {
//     size?: number | string;
//   }

//   export const JSIcon = memo(({ size, ...rest }: Props) => (
//     <Javascript style={{ width: size, height: size }} {...rest} />
//   ));
//   export const PythonIcon = memo(({ size, ...rest }: Props) => (
//     <Python style={{ width: size, height: size }} {...rest} />
//   ));
//   export const CSharpIcon = memo(({ size, ...rest }: Props) => (
//     <Csharp style={{ width: size, height: size }} {...rest} />
//   ));
//   export const CurlIcon = memo(({ size, ...rest }: Props) => (
//     <Curl style={{ width: size, height: size }} {...rest} />
//   ));
